### PR TITLE
first shot at implementing https://github.com/yarl/vicuna/issues/98

### PR DESCRIPTION
**Pull request by FlominatorTM**
I don't know if it's bold the simply retrieve that field all the time, but I thought I give it a shot anyway ...

### CODE REVIEW

**Comment by saper** [comment]
Looks good to me, do you have some test files to try it on?

Also there is something wrong with the whitespace, have a look at your git show output

**Comment by FlominatorTM** [comment]
@saper Thanks for having a look at it. I'm not 100% sure (currently not at my machine), but according to metadata information https://commons.wikimedia.org/wiki/File:%28Wasser-%29Schloss_Birkenreute_in_Kirchzarten_2.jpg should have this IPTC data.

Can you give me a hint on what exactly to look for regarding the whitespace?

**Comment by saper** [comment]
Sure, just have a look at https://github.com/yarl/vicuna/pull/102/files and you will see that some lines are moved to the right strangely. Most probably you have tabs somewhere where we use spaces.

Also avoid adding empty new lines if not necessary.

**Comment by FlominatorTM** [comment]
Better like this? Thank you for your patience, this is my first pull-request that I get feedback for :)

**Comment by FlominatorTM** [comment]
@saper Is the additional commit better regarding indention?

**Comment by michal-josef-spacek** [comment]
Rewrite this PR to #157

**Pull request closed without merging**
